---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


***Creating a flexdashboard***
```{r include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(viridis)
data("instacart")
```





{data-width=650}
-----------------------------------------------------------------------
### Chart A

```{r echo=FALSE}

library(plotly)

instacart %>%
  group_by(order_hour_of_day, department) %>%
  count() %>%
  plot_ly(
    x = ~order_hour_of_day,
    y = ~n,
    type = "scatter",
    mode = "lines+markers",
    color = ~department,
    colors = "viridis"
  ) %>%
  layout(
    title = "Number of Snack Orders by Hour of the Day",
    xaxis = list(title = "Hour of the Day"),
    yaxis = list(title = "Number of Snack Orders")
  )

```

{data-width=350}
-----------------------------------------------------------------------
### Chart B

```{r echo=FALSE}
data("instacart")


instacart %>%
  group_by(order_hour_of_day, department) %>%
  count() %>%
  plot_ly(
    x = ~department,
    y = ~n,
    type = "box",
    marker = list(color = ~department, colors = "viridis")
  ) %>%
  layout(
    title = "Number of Snack Orders by Department",
    xaxis = list(title = "Department"),
    yaxis = list(title = "Number of Snack Orders")
  )


```



Column {data-width=650}
-----------------------------------------------------------------------

### Chart C

```{r echo=FALSE}
data("instacart")

filtered_aisles = instacart %>%
  group_by(aisle, department) %>%
  summarise(item_count = n(), .groups = "drop") %>%
  filter(item_count > 10000) %>%
  arrange(item_count)

plot_ly(data = filtered_aisles, x = ~aisle, y = ~item_count, color = ~department, type = "bar", colors = "viridis") %>%
  layout(title = "Items Ordered Over 10000 times from Each Aisle",
         xaxis = list(title = "Aisle Names"),
         yaxis = list(title = "Number of Items Ordered"))

```




